# Generated by Django 5.2.7 on 2025-11-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('font', models.CharField(default='arial', max_length=50)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('shirt_color', models.CharField(default='white', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mockups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
